### PR TITLE
Higher-order effects

### LINKED ISSUE #47: Interposing is ignorant of other effect handlers
This came up most recently in the context of #46, but we’ve seen it in a few different contexts overall. I’m aware of three useful lenses on the problem, so I’ll try to detail each of them.

1. `interpose` applies only to the effects inside it, not whatever effects they’re handled with.

    If you use resumable exceptions, `Yield`, or some effect-as-abstraction which hides the implementation details behind its requests & handlers, you have to be aware of the interactions with e.g. `Exc` and `Reader`. `catchError` and `local` both use `interpose` to intercept requests, but only within the action passed to them at the time at which they were called.

    Thus, `local (+ (1 :: Int)) (send Foo)` will increment the context value for any `ask`s or further `local` inside the action it receives, `send Foo`, and _not_ whatever action _handles_ `send Foo`. Since there are no `Reader` actions within `send Foo` itself (only `Foo`, whatever that is), it’s as if we hadn’t bothered using `local` at all.

2. Effects inserted by handlers (`relay`, etc) are run in the context at which the handler is called, not in the context of the effects they’re handling; or, handlers can inject values, but not effects, into effectful actions.

    This is easiest to demonstrate by zooming out a bit from the `local` handler described above to encompass the `Foo` and `Reader` handlers as well:

    ```haskell
    data Foo result where
      Foo :: Foo Int

    testFoo :: Eff '[] Int
    testFoo = runReader (0 :: Int) (relay pure (\ Foo yield -> ask >>= yield) (local (+ (1 :: Int)) (send Foo)))
    ```

    The `relay` handling `Foo` is free to send `Reader` requests, since `Reader` is handled above it. However, these requests are made in the context `relay` is called at, which only has the top-level `runReader` handler present, and not where the `Foo` effect is sent. Thus, the result of `testFoo` will be `0`, despite the `local` increment—sending the `Foo` effect escapes from the `local` context and there’s no way to un-escape.

    This is the case even tho we’re calling `yield` to provide the `Int` back to the sending context—so we can inject values back in, but not effects. That takes us to the third angle on this.

3. Higher-order effects are inflexible.

    The one exception I’m aware of to the rule that handlers can inject values but not effects is if we have what I’m terming a _higher-order effect_, i.e. an effect whose result is an effectful action. We can define `Foo` thus by changing its result type:

    ```haskell
    data Foo result where
      Foo :: Foo (Eff '[Foo, Reader Int] Int)
    ```

    Rather than encoding a request for an `Int`, `Foo` is now a request for an `Eff` producing an `Int`. Since we’ve changed the result type of `Foo`, we must also change its handler and requests:

    ```haskell
    testFoo :: Eff '[] Int
    testFoo = runReader (0 :: Int) (relay pure (\ Foo yield -> yield ask) (local (+ (1 :: Int)) (join (send Foo))))
    ```

    Note that we’re `yield`ing the `ask` action (rather than its result), and `join`ing the result of the `send`. Now, the result of `run testFoo` is (correctly) `1`, which is exactly the behaviour we want. Furthermore, it’s clear that the change to the semantics of the request are the only sensible way of injecting effects into an action; the effect has to specify that they’ll occur, the code making the request has to request and `join` them, and the handler has to satisfy that request with an effectful action.

    Unfortunately, this comes at a significant cost to flexibility. `Foo`’s result type enumerates all of the effects it’s able to perform. This same problem exists with `Embedded`, which makes it easier to encode a _smaller_ list of effects, but in no way addresses the need to enumerate them. (Furthermore, as `Embedded` requests hold an `Eff` and return an `a`, they’re only able to express the passing of an action to a handler, rather than the handling of an effect by passing an action back.)

    This can pose a serious barrier to implementation, since we have to be careful not to mention the effects list itself, i.e. the naïve `Member (Reader (Eff effects Int)) effects` constraint we would wish to be able to employ is unsolvable due its request for the occurrence of `effects` within `effects`—and so we can’t actually handle the effect.

    The reason becomes obvious when you try to give a type for the handler: we start with `Eff (Reader _ ': effects) a -> Eff effects a`, and then try to fill in the hole. But since it’s self-referential, we have to fill it in with `Eff (Reader _ ': effects) Int`, and then again, ad infinitum. Attempts to resolve this with a type equality constraint on `effects` also fail, and while it’s not explicitly mentioned, I believe it’s due to the occurs check.

    When needing to break a cycle like this, the obvious solution is to employ a `newtype`, which we can indeed use successfully here. However, this is really just moving the problem around. While something like this:

    ```haskell
    newtype Inner = Inner { runInner :: Eff (Reader (Inner effects Int) ': effects) a }
    ```

    does enable us to write the handler, now the actions making requests have to be aware that a) they need to use & unwrap `Inner`, and b) that it’s at the head of the effect list (a constraint imposed by `Inner` itself). While the former problem is quite minor, the latter means that they instantly become very inflexible, and can’t easily be run in different contexts.

These three problems—really the same problem—are the cause of significant complexity in our use cases. I think we _might_ be able to make some headway by having `Eff` provide effects with the effect list as a parameter, but I’m not at all certain of that.

It’s also entirely possible that this is just a reality of using this system. In that case, we should at least document some best practices for handling these sorts of situations.

### LINKED ISSUE #52: The inferred type roles for Union (and therefore Eff) are wrong
`Union` doesn’t visibly use its member list, so its inferred type role is `phantom`, which is wrong. It should probably be `nominal` (I’m not sure it shouldn’t be `representational`, but maybe).

The same therefore applies to `Eff`.

Unfortunately, we rely on this behaviour to embed effects in values, so any resolution to this should come hand-in-hand with a resolution to #47, i.e. higher-order effects.

### PR DESCRIPTION
**Pull request by robrix**
This PR:

- [x] Redefines effects using higher-order syntax à la _Effect Handlers in Scope_.
- [x] Replaces the handler functions with pattern synonyms for writing effect handlers.
- [x] ~~Replaces interposition with _scoped effects_.~~ Scoped effects are good, but interposition typechecks just fine as-is.
- [x] Define an `Effect` instance for `Resumable`.
- [x] ~~Assume `Effect` instances in the `E` constructor so we can avoid having to add constraints everywhere.~~ This doesn’t work out.
- [x] ~~Can we define the pattern synonyms against `Effectful` instead of `Eff`?~~ No:
    ```
    ghc: panic! (the 'impossible' happened)
      (GHC version 8.2.2 for x86_64-apple-darwin):
    	mkOneConFull: Not TyConApp:
      a_abvsh (Eff (a_abvsh : effects_abtE6)) b_dbvv3
      Call stack:
          CallStack (from HasCallStack):
            prettyCurrentCallStack, called at compiler/utils/Outputable.hs:1133:58 in ghc:Outputable
            callStackDoc, called at compiler/utils/Outputable.hs:1137:37 in ghc:Outputable
            pprPanic, called at compiler/deSugar/Check.hs:976:30 in ghc:Check
    ```
- [x] Can we return `Eff` or `Effectful` from `handle` & `handleState` and 🔥 `fromRequest`?
- [x] Can we make `handle` & `handleState` take explicit continuations and provide same in `Other`?
  - [x] ~~Can we then 🔥 `Request`?~~ Not really, we kind of need it for `handleState`.
- [x] ~~Can we define `relay`/`relayState` again?~~ Not as far as I can see, tho possibly if we limited it to specific functors. But in general, if you wanted `relay`/`relayState` before, you want to use the pattern synonyms now.
- [x] 📝 everything.
- [x] Fix the tests.
- [x] Figure out what to do with `Embedded`.
- [x] Fixes #47.
- [x] Fixes #52.

### CODE REVIEW

**Comment by robrix** [comment]
I’m pleased to report that this works just fine for refinement-style handlers—in particular, they now play nicely with `Reader`.

File: examples/src/Teletype.hs [hunk 1]
```diff
@@ -1,17 +1,17 @@
...
 
 import Control.Monad.Effect
 import Control.Monad.Effect.Internal as I
 import System.Exit hiding (ExitSuccess)
 
-data Teletype s where
-  PutStrLn    :: String -> Teletype ()
-  GetLine     :: Teletype String
-  ExitSuccess :: Teletype ()
+data Teletype (m :: * -> *) s where
```
Comment (robrix) [inline examples/src/Teletype.hs]: All effects now receive this extra parameter, populated with an `Eff`, whose effect list gets smaller and smaller as other effects are handled.

File: src/Control/Monad/Effect/Embedded.hs [hunk 2]
```diff
@@ -1,64 +0,0 @@
...
-{-# LANGUAGE GADTs #-}
-{-# LANGUAGE FlexibleContexts #-}
-{-# LANGUAGE FlexibleInstances #-}
-{-# LANGUAGE KindSignatures #-}
-{-# LANGUAGE MultiParamTypeClasses #-}
-{-# LANGUAGE RankNTypes #-}
-{-# LANGUAGE TypeApplications #-}
-{-# LANGUAGE TypeOperators #-}
-
-module Control.Monad.Effect.Embedded (
```
Comment (robrix) [inline src/Control/Monad/Effect/Embedded.hs]: Since all effects can embed `Eff`s, there’s not much call for this one.

File: src/Control/Monad/Effect/Exception.hs [hunk 3]
```diff
@@ -43,19 +39,22 @@ import Control.Monad.Effect.Internal
                            -- Exceptions --
 --------------------------------------------------------------------------------
 -- | Exceptions of the type 'exc'; no resumption
-newtype Exc exc a = Exc exc
+newtype Exc exc (m :: * -> *) a where
+  Throw :: exc -> Exc exc m a
```
Comment (robrix) [inline src/Control/Monad/Effect/Exception.hs]: I renamed the constructor in anticipation that we might eventually add `Catch` as a scoped effect.

File: src/Control/Monad/Effect/Fail.hs [hunk 4]
```diff
@@ -8,5 +8,8 @@ module Control.Monad.Effect.Fail
 import Control.Monad.Effect.Internal
 import Control.Monad.Fail
 
-runFail :: Effectful m => m (Fail ': fs) a -> m fs (Either String a)
-runFail = raiseHandler (relay (pure . Right) (const . pure . Left . failMessage))
+runFail :: (Effectful m, Effect (Union effs)) => m (Fail ': effs) a -> m effs (Either String a)
+runFail = raiseHandler go
+  where go (Return a)          = pure (Right a)
+        go (Effect (Fail s) _) = pure (Left s)
+        go (Other u k)         = liftStatefulHandler (Right ()) (either (pure . Left) runFail) u k
```
Comment (robrix) [inline src/Control/Monad/Effect/Fail.hs]: The need to handle effects within other effects means that we can no longer express the extremely general form of `relay`. Therefore, effect handlers are instead defined with this straightforward suite of pattern matches, comprising the exhaustive set of cases for `Eff`: a pure return value, the effect being handled, or some other effect through which we must thread our handler.

In the case of `runFail`, we use `liftStatefulHandler` because we’re encoding the result in a functorial return value (`Either String`), and thus the initial state is trivially `Right ()`.

File: src/Control/Monad/Effect/Fresh.hs [hunk 5]
```diff
@@ -43,5 +44,11 @@ resetFresh :: (Effectful m, Member Fresh effects) => Int -> m effects a -> m eff
 resetFresh start = raiseHandler (interposeState start (const pure) (\ counter Fresh yield -> (yield $! succ counter) counter))
 
 -- | Handler for Fresh effects, with an Int for a starting value
-runFresh :: Effectful m => Int -> m (Fresh ': e) a -> m e a
-runFresh s = raiseHandler (relayState s (const pure) (\s' Fresh k -> (k $! s'+1) s'))
+runFresh :: (Effectful m, Effect (Union e)) => Int -> m (Fresh ': e) a -> m e a
+runFresh s = raiseHandler $ fmap snd . runState s . reinterpret (\ Fresh -> do
+  s' <- get
+  s' <$ (put $! succ s'))
```
Comment (robrix) [inline src/Control/Monad/Effect/Fresh.hs]: I opted to reinterpret `Fresh` in terms of `State` rather than handling it specially.

File: src/Control/Monad/Effect/Internal.hs [hunk 6]
```diff
@@ -37,36 +38,112 @@ module Control.Monad.Effect.Internal (
...
+pattern Effect2_1 eff k <- (decomposeEff -> Right (Request (decompose -> Right eff) k))
+
+-- | The second of the topmost two effects in the 'Union', and the continuation following it.
+pattern Effect2_2 :: effect2 (Eff (effect1 ': effect2 ': effects)) b -> Arrow (Eff (effect1 ': effect2 ': effects)) b a -> Eff (effect1 ': effect2 ': effects) a
+pattern Effect2_2 eff k <- (decomposeEff -> Right (Request (decompose -> Left (decompose -> Right eff)) k))
+
+-- | Another effect in the 'Union', and the continuation following it.
+pattern Other2 :: Union effects (Eff (effect1 ': effect2 ': effects)) b -> Arrow (Eff (effect1 ': effect2 ': effects)) b a -> Eff (effect1 ': effect2 ': effects) a
+pattern Other2 u k <- (decomposeEff -> Right (Request (decompose -> Left (decompose -> Left u)) k))
+{-# COMPLETE Return, Effect2_1, Effect2_2, Other2 #-}
```
Comment (robrix) [inline src/Control/Monad/Effect/Internal.hs]: We can have multiple complete sets of patterns, which enables us to deal with cases handling a single effect and cases handling a pair of effects using convenient synonyms.

File: src/Control/Monad/Effect/Internal.hs [hunk 7]
```diff
@@ -37,36 +38,112 @@ module Control.Monad.Effect.Internal (
...
+-- | Effects are higher-order (may themselves contain effectful actions), and as such must be able to thread an effect handler (structured as a distributive law) through themselves.
+class Effect effect where
+  -- | Lift some initial state and a handler for some effect through another effect.
+  --
+  --   First-order effects (ones not using the @m@ parameter) have relatively simple definitions, more or less just pushing the distributive law through the continuation. Higher-order effects (like @Reader@’s @Local@ constructor) must additionally apply the handler to their scoped actions.
+  handleState :: Functor c
+              => c ()
+              -> (forall x . c (Eff effects x) -> Eff effects' (c x))
+              -> Request effect (Eff effects) a
+              -> Request effect (Eff effects') (c a)
```
Comment (robrix) [inline src/Control/Monad/Effect/Internal.hs]: Every effect must have an `Effect` instance, which consists of a single function to thread a handler through it.

File: src/Control/Monad/Effect/Internal.hs [hunk 8]
```diff
@@ -37,36 +38,112 @@ module Control.Monad.Effect.Internal (
...
+
+-- | Lift a stateful effect handler through other effects in the 'Union'.
+--
+--   Useful when defining effect handlers which maintain some state (such as @runState@) or which must return values in some carrier functor encapsulating the effects (such as @runError@).
+liftStatefulHandler :: (Functor c, Effects effects') => c () -> (forall x . c (Eff effects x) -> Eff effects' (c x)) -> Union effects' (Eff effects) b -> Arrow (Eff effects) b a -> Eff effects' (c a)
+liftStatefulHandler c handler u k = fromRequest (handleState c handler (Request u k))
```
Comment (robrix) [inline src/Control/Monad/Effect/Internal.hs]: Effects which aren’t handled using `interpret` or `reinterpret` must instead have handlers written using the pattern synonyms and either `liftStatefulHandler` or `liftHandler`.

File: src/Control/Monad/Effect/Internal.hs [hunk 9]
```diff
@@ -136,56 +222,23 @@ run m = case lowerEff m of
...
+runM :: (Effectful m, Monad m1) => m '[Lift m1] a -> m1 a
 runM m = case lowerEff m of
-  Val x -> pure x
-  E u q -> case decompose u of
-    Right m' -> m' >>= runM . apply q
-    Left _   -> error "Internal:runM - This (Left) should never happen"
-
--- | Given an effect request, either handle it with the given 'pure' function,
--- or relay it to the given 'bind' function.
-relay :: Effectful m
```
Comment (robrix) [inline src/Control/Monad/Effect/Internal.hs]: Sadly, `relay` and `relayState` are too general for us to express now that we have to handle embedded effects.

We _might_ be able to recover an analogue of `relayState` constrained to functorial return values, but I wasn’t having much luck encoding that, and the alternative (writing handlers using the pattern synonyms) is quite usable.

File: src/Control/Monad/Effect/Internal.hs [hunk 10]
```diff
@@ -195,78 +248,94 @@ interpose pure' h = raiseHandler loop
...
+-- * Effect handlers
+
 -- | Handle the topmost effect by interpreting it into the underlying effects.
-interpret :: Effectful m => (forall a. eff a -> m effs a) -> m (eff ': effs) b -> m effs b
-interpret handler = raiseHandler (relay pure (\ eff yield -> lowerEff (handler eff) >>= yield))
+interpret :: (Effectful m, Effects effs)
+          => (forall v. eff (Eff (eff ': effs)) v -> m effs v)
+          -> m (eff ': effs) a
+          -> m effs a
+interpret bind = raiseHandler loop
```
Comment (robrix) [inline src/Control/Monad/Effect/Internal.hs]: Fortunately, `interpret` and `reinterpret` can still be expressed since they don’t change the return type.

File: src/Control/Monad/Effect/Internal.hs [hunk 11]
```diff
@@ -136,56 +222,23 @@ run m = case lowerEff m of
...
 interpose :: (Member eff e, Effectful m)
-          => Arrow m e a b
-          -> (forall v. eff v -> Arrow m e v b -> m e b)
+          => Arrow (m e) a b
+          -> (forall v. eff (Eff e) v -> Arrow (m e) v b -> m e b)
           -> m e a -> m e b
 interpose pure' h = raiseHandler loop
  where
-   loop (Val x) = lowerEff (pure' x)
+   loop (Return x) = lowerEff (pure' x)
```
Comment (robrix) [inline src/Control/Monad/Effect/Internal.hs]: `interpose` and `interposeState` are still expressible, with only a tweak to the pure constructor’s name.

File: src/Control/Monad/Effect/Internal.hs [hunk 12]
```diff
@@ -195,78 +248,94 @@ interpose pure' h = raiseHandler loop
...
-instance Member IO e => MonadIO (Eff e) where
-  liftIO = send
+instance Member (Lift IO) e => MonadIO (Eff e) where
+  liftIO = send . Lift
   {-# INLINE liftIO #-}
 
 
+-- | Lift a first-order effect (e.g. a 'Monad' like 'IO') into an 'Eff'.
+newtype Lift effect (m :: * -> *) a = Lift { unLift :: effect a }
+  deriving (Eq, Foldable, Functor, Ord, Show, Traversable)
```
Comment (robrix) [inline src/Control/Monad/Effect/Internal.hs]: Since effects are now `(* -> *) -> (* -> *)` instead of `* -> *`, lifting existing `Monad`s (most commonly `IO`) into `Eff` now uses this `Lift` helper. Note that `m`, the embedded effect, is phantom; this differs from the presentation in _Effect Handlers in Scope_, where `effect` is parameterized by `m a` instead of `a`. This difference accommodates the fact that rather than depending on functorial effects, we express the capacity for further effectful actions in the queue; thus, there’s no need to constrain `effect` to contain `m`s.

File: src/Control/Monad/Effect/Internal.hs [hunk 13]
```diff
@@ -276,9 +345,16 @@ instance Member NonDet a => MonadPlus (Eff a) where
   mzero       = send MZero
   mplus m1 m2 = send MPlus >>= \x -> if x then m1 else m2
 
+instance Effect NonDet where
+  handleState c dist (Request MZero k) = Request MZero (dist . (<$ c) . k)
+  handleState c dist (Request MPlus k) = Request MPlus (dist . (<$ c) . k)
```
Comment (robrix) [inline src/Control/Monad/Effect/Internal.hs]: First-order effects have trivial `Effect` instances, which pretty much universally look like this, just distributing the handler through the continuation.

File: src/Control/Monad/Effect/NonDet.hs [hunk 14]
```diff
@@ -43,15 +44,27 @@ gatherM f = raiseHandler (interpose (pure . f) (\ m k -> case m of
...
+
+-- | A handler for nondeterminstic effects
+runNonDet :: (Effectful m, Effects e)
+           => m (NonDet ': e) a
+           -> m e [a]
+runNonDet = raiseHandler go
+  where go (Return a)       = pure [a]
+        go (Effect MZero _) = pure []
+        go (Effect MPlus k) = liftA2 (++) (runNonDetA (k True)) (runNonDetA (k False))
+        go (Other u k)      = liftStatefulHandler [] (fmap join . traverse runNonDetA) u k
```
Comment (robrix) [inline src/Control/Monad/Effect/NonDet.hs]: It took me a while to figure out how to write this. Basically, you can’t write `runNonDetA` directly because of some the functor is polymorphic and we don’t know how to interpret its contents in the second parameter. Instead, `runNonDet` interprets into a `[]`, which is monomorphic and easy to interpret, and then `runNonDetA` and `runNonDetM` are backwards-compatible wrappers around it.

We also export `runNonDet` so that clients wishing to generate lists don’t have to do a redundant (if probably fused away) reinterpretation of the list into a list.

File: src/Control/Monad/Effect/NonDet.hs [hunk 15]
```diff
@@ -43,15 +44,27 @@ gatherM f = raiseHandler (interpose (pure . f) (\ m k -> case m of
...
+
+-- FIXME: It would probably be more efficient to define these in terms of a binary tree rather than a list.
```
Comment (robrix) [inline src/Control/Monad/Effect/NonDet.hs]: This is left as work for a future PR; unfortunately I didn’t have much luck defining this using an accumulator parameter, but it might be worth revisiting at some point.

File: src/Control/Monad/Effect/NonDet.hs [hunk 16]
```diff
@@ -43,15 +44,27 @@ gatherM f = raiseHandler (interpose (pure . f) (\ m k -> case m of
...
 
 msplit :: (Member NonDet e, Effectful m)
        => m e a -> m e (Maybe (a, m e a))
-msplit = raiseHandler (fmap (fmap (second raiseEff)) . loop [])
-  where loop jq (Val x) = pure (Just (x, msum jq))
+msplit = raiseHandler (fmap (fmap (fmap raiseEff)) . loop [])
```
Comment (robrix) [inline src/Control/Monad/Effect/NonDet.hs]: Much like `interpose`, `msplit` works with trivial alterations. `msplit` is quite a sophisticated operator, so this was a good sign.

File: src/Control/Monad/Effect/Reader.hs [hunk 17]
```diff
@@ -38,8 +38,9 @@ module Control.Monad.Effect.Reader (
 import Control.Monad.Effect.Internal
 
 -- |
-data Reader v a where
-  Reader :: Reader a a
+data Reader v (m :: * -> *) a where
+  Reader :: Reader a m a
+  Local :: (v -> v) -> m a -> Reader v m a
```
Comment (robrix) [inline src/Control/Monad/Effect/Reader.hs]: This is at present the only scoped effect in the library.

File: src/Control/Monad/Effect/Reader.hs [hunk 18]
```diff
@@ -50,21 +51,26 @@ asks :: (Member (Reader v) e, Effectful m) => (v -> a) -> m e a
...
-  let e = f e0
-  let bind :: Reader v a -> Arrow Eff e a b -> Eff e b
-      bind Reader g = g e
-  interpose pure bind (lowerEff m)
+local f m = send (Local f (lowerEff m))
+
+
+instance Effect (Reader r) where
+  handleState c dist (Request Reader k) = Request Reader (dist . (<$ c) . k)
+  handleState c dist (Request (Local f a) k) = Request (Local f (dist (a <$ c))) (dist . fmap k)
```
Comment (robrix) [inline src/Control/Monad/Effect/Reader.hs]: Since this effect contains a scope, we must handle effects within it as well as passing it through the continuation.

File: src/Control/Monad/Effect/StateRW.hs [hunk 19]
```diff
@@ -33,14 +33,11 @@ import Control.Monad.Effect.Writer
...
-       Left u'' -> E u'' (tsingleton (k s'))
-    where k s'' = q >>> loop s''
+runStateR :: (Effectful m, Effect (Union e)) => s -> m (Writer s ': Reader s ': e) a -> m e (s, a)
+runStateR = raiseHandler . go
+  where go :: Effect (Union e) => s -> Eff (Writer s ': Reader s ': e) a -> Eff e (s, a)
+        go s (Return a)                = pure (s, a)
+        go _ (Effect2_1 (Writer s) k)  = go s (k ())
+        go s (Effect2_2 Reader k)      = go s (k s)
+        go s (Effect2_2 (Local f m) k) = go (f s) (m >>= k)
+        go s (Other2 u k)              = liftStatefulHandler (s, ()) (uncurry runStateR) u k
```
Comment (robrix) [inline src/Control/Monad/Effect/StateRW.hs]: Handling two effects at once is not much more complicated than one at a time.

File: src/Control/Monad/Effect/State.hs [hunk 20]
```diff
@@ -39,16 +39,18 @@ import Data.Proxy
...
-runState :: Effectful m => s -> m (State s ': e) b -> m e (b, s)
-runState initial = relayState initial (\ s b -> raiseEff (pure (b, s))) (\ s eff yield -> case eff of
-  Get    -> yield s s
-  Put s' -> yield s' ())
+runState :: (Effectful m, Effect (Union e)) => s -> m (State s ': e) b -> m e (s, b)
+runState = raiseHandler . go
+  where go s (Return a)         = pure (s, a)
+        go s (Effect Get k)     = runState s (k s)
+        go _ (Effect (Put s) k) = runState s (k ())
+        go s (Other u k)        = liftStatefulHandler (s, ()) (uncurry runState) u k
```
Comment (robrix) [inline src/Control/Monad/Effect/State.hs]: The requirement to encode state in a functor necessitated the swapping of the order of all of the pairs, since `(s, _)` is a `Functor` but `(_, s)` is not, in Haskell.

That `uncurry runState` turned out quite beautifully, I think.

File: src/Data/Union.hs [hunk 21]
```diff
@@ -39,90 +27,80 @@ universe.
...
--- No other case is possible
-{-# RULES "decompose/singleton"  decompose = decompose0 #-}
-{-# INLINE decompose0 #-}
-
-weaken :: Union r w -> Union (any ': r) w
+weaken :: Union r f v -> Union (any ': r) f v
 weaken (Union n v) = Union (n+1) v
 
+strengthen :: Union '[last] f v -> last f v
+strengthen (Union _ t) = unsafeCoerce t
```
Comment (robrix) [inline src/Data/Union.hs]: This avoids the need for some partiality in `Control.Monad.Effect.Internal`.

File: src/Data/Union.hs [hunk 22]
```diff
@@ -39,90 +27,80 @@ universe.
...
-      MemberU' (f::Bool) (tag :: (* -> *) -> * -> *) (t :: * -> *) r | tag r -> t
+prj' :: Int -> Union r f v -> Maybe (t f v)
+prj' n (Union n' x) | n == n'   = Just (unsafeCoerce x)
+                    | otherwise = Nothing
+{-# INLINE prj' #-}
 
-instance MemberU' 'True tag (tag e) (tag e ': r)
-instance (Member t (t' ': r), MemberU2 tag t r) =>
-           MemberU' 'False tag t (t' ': r)
+newtype Offset (t :: (* -> *) -> (* -> *)) (r :: [(* -> *) -> (* -> *)]) = Offset { getOffset :: Int }
```
Comment (robrix) [inline src/Data/Union.hs]: I finally got sick of `P`.

File: src/Data/Union.hs [hunk 23]
```diff
@@ -39,90 +27,80 @@ universe.
...
 
-module Data.Union (
-  Union,
-  decompose,
-  weaken,
-  inj,
-  prj,
-  Member,
-  MemberU2,
+module Data.Union
```
Comment (robrix) [inline src/Data/Union.hs]: The changes to `Union` are mostly to accommodate the higher kind.

File: src/Control/Monad/Effect/Internal.hs [hunk 24]
```diff
@@ -37,36 +38,112 @@ module Control.Monad.Effect.Internal (
...
+import Data.Coerce
 import Data.FTCQueue
+import Data.Functor.Identity
+import Data.Union
 
 -- | An effectful computation that returns 'b' and sends a list of 'effects'.
 data Eff effects b
   -- | Done with the value of type `b`.
-  = Val b
+  = Return b
```
Comment (joshvera) [inline src/Control/Monad/Effect/Internal.hs]: Maybe `Pure`?

Comment (robrix) [reply src/Control/Monad/Effect/Internal.hs]: We can go with that, but I kind of like how it reads since `Return` is always a return value. (It gets eliminated by the definitions of `<*>` and `>>=` any time it appears in non-final position.)

**Comment by robrix** [comment]
Pretty sure `interpose` is wrong, so putting this back to WIP.

File: src/Control/Monad/Effect/Internal.hs [hunk 25]
```diff
@@ -136,137 +222,114 @@ run m = case lowerEff m of
...
+-- | Listen for an effect, and take some action before re-sending it.
+eavesdrop :: (Member eff effects, Effectful m, Effects effects)
+          => (forall v. eff (Eff effects) v -> m effects ())
+          -> m effects a
+          -> m effects a
+eavesdrop listener = raiseHandler loop
+  where loop (Return a) = pure a
+        loop (E u q) = case prj u of
+          Just eff -> lowerEff (listener eff) >> send eff >>= (q >>> loop)
+          _        -> liftHandler (eavesdrop (lowerEff . listener)) u (q >>> loop)
```
Comment (robrix) [inline src/Control/Monad/Effect/Internal.hs]: I’m not certain, but this might be infinite looping.

**Comment by robrix** [comment]
> I’d like to explore a new-style `interposeState` again in a separate PR.

It doesn’t work out properly.

**Comment by robrix** [comment]
@joshvera: Are you cool with merging with `Return` instead of `Pure`? And/or do you want to re-review?
